services:
  api-dofuspulse:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: api-dofuspulse
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - FRONTEND_HOST=${FRONTEND_HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    depends_on:
      - timescaledb

  web-dofuspulse:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: web-dofuspulse
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-dofuspulse

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:



